version: '2'
services:
  gameswithwords:
    image: gameswithwords:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links: 
      - rabbit
  rabbit:
    image: rabbitmq